(ns gen-icons
  "Generates src/notebox/ui/icons.cljc from the Figma exports in
  spec/design/assets/*.svg: each SVG becomes data that notebox.ui.rn.svg
  renders with react-native-svg. Filters (drop shadows) are dropped.

  Run: clojure -M -m gen-icons  (with scripts/ on the classpath: -Sdeps '{:paths [\"scripts\"]}')"
  (:require [clojure.java.io :as io]
            [clojure.pprint :as pp]
            [clojure.string :as str]
            [clojure.xml :as xml]))

(def assets-dir "spec/design/assets")
(def out-file "src/notebox/ui/icons.cljc")

(def kept-tags #{:g :path :rect :line :circle})
(def dropped-attrs #{:id :filter :style :overflow :preserveAspectRatio})

(defn camel [k]
  (let [[h & t] (str/split (name k) #"-")]
    (keyword (apply str h (map str/capitalize t)))))

(defn- number-or-string [s]
  (if (re-matches #"-?\d+(\.\d+)?" s) (Double/parseDouble s) s))

(defn element [{:keys [tag attrs content]}]
  (when (kept-tags tag)
    (let [attrs (into (sorted-map)
                      (for [[k v] attrs :when (not (dropped-attrs k))]
                        [(camel k) (if (#{:d :fill :stroke :transform :fillRule :clipRule :strokeLinecap} (camel k))
                                     v
                                     (number-or-string v))]))
          children (keep element content)]
      (cond-> [tag attrs] (seq children) (into children)))))

(defn icon [file]
  (let [{:keys [attrs content]} (xml/parse file)]
    (cond-> {:width    (number-or-string (:width attrs))
             :height   (number-or-string (:height attrs))
             :view-box (:viewBox attrs)
             :children (vec (keep element content))}
      ;; the root's fill (often "none") is inherited by every shape
      (:fill attrs) (assoc :fill (:fill attrs)))))

(defn -main [& _]
  (let [files (sort-by #(.getName %) (filter #(str/ends-with? (.getName %) ".svg")
                                             (.listFiles (io/file assets-dir))))
        icons (into (sorted-map) (for [f files]
                                   [(keyword (str/replace (.getName f) #"\.svg$" "")) (icon f)]))]
    (spit out-file
          (str ";; GENERATED by scripts/gen_icons.clj from spec/design/assets/*.svg — don't edit.\n"
               "(ns notebox.ui.icons\n"
               "  \"Icons, logo and illustrations from the Figma design, as SVG data for\n"
               "  notebox.ui.rn.svg/svg. Drop shadows are left out.\")\n\n"
               "(def icons\n"
               (with-out-str (pp/pprint icons))
               ")\n"))
    (println "wrote" out-file (count icons) "icons")))
